### ISSUE TITLE
Доп Задача 2

### ISSUE THREAD

**Issue by keplian** [extroot/oldDjango#1]
Хорошая структура приложений в репозитории. Молодец, что хорошо оформил хранение и чтение переменных окружений в settings
Но некоторые моменты следует отработать. Давай посмотрим.

## **Urls** ##
Ты верно сделал, что использовал регулярки. Однако, не поставил открывающие и закрывающие якоря (` ^` и `$`) для строк.  Это приводит к тому, что джанго будет принимать ЛЮБУЮ строку, содержащую, к примеру` '/users' `, и считать, что она верная. Как пример, все запросы к подобный адресам будут успешны, вот пример, когда я запустил твое приложение:
```
[18/Mar/2022 07:40:47] "GET /auth/users/ HTTP/1.1" 200 48
[18/Mar/2022 07:40:52] "GET /auth/12222users/ HTTP/1.1" 200 48
[18/Mar/2022 07:41:02] "GET /auth/12222userssdasdadsdasdasdsad/ HTTP/1.1" 200 23
```
Согласись, это не совсем то, что мы хотим?
исправь, добавив ко ВСЕМ адресам, где используешь регулярки, якоря.

**Comment by extroot** [comment]
Исправлено.
